# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('uniprot', models.CharField(max_length=140)),
                ('degree_centrality', models.DecimalField(decimal_places=10, max_digits=50)),
                ('betweenness_centrality', models.DecimalField(decimal_places=10, max_digits=50)),
            ],
        ),
    ]
